### ISSUE TITLE
State transformation in useEntity hangs browser

### ISSUE THREAD

**Issue by romgerman** [arnelenero/simpler-state#15] opened 2021-07-26 09:20 UTC
**Describe the bug**
Trying to use `Array.map` inside `tranform` argument hangs Chrome 91

Getting `Too many re-renders. React limits the number of renders to prevent an infinite loop`

**To Reproduce**
Create an entity with `items` property and try to use in `useEntity` with some transformations
```js
// In state file
const StateEntity = entity({ items: [/*your items*/] })

// In component
const items = useEntity(StateEntity, s=> s.items.map(x => ({...x, newProp: true}));
```
(https://codesandbox.io/s/zealous-almeida-l9qs6?file=/src/App.tsx)

**Expected behavior**
State transforms as it updates and doesn't hang browser

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H1
 - Browser: Chrome
 - Version: 91.0.4472.164

**Comment by romgerman** [comment] 2021-07-26 09:52
Also occurs with `Array.filter`

**Comment by arnelenero** [comment] 2021-07-27 14:13
Thanks for submitting your feedback.

I see perfectly fine logic behind why your transform function is defined as such.  However, because of the way React defines an "updated state" (nothing to do with simpler-state itself), simply using `Array.map` without some form of memoization will always return a fresh array, thus triggering a re-render.

There are ways of memoizing within your transform function (such as using _reselect_ library), but here is a  much simpler solution you can consider, which relies on `useMemo` instead of a transform fn:

```js
// In state file
const stateEntity = entity({ items: [/*your items*/] })

// In component

const  state = useEntity(stateEntity);
const items = useMemo(() => state.items.map(x => ({...x, newProp: true}), [state]);
```

This does not appear to necessitate a change in simpler-state itself, but let me know if you encounter further issues.

**Comment by romgerman** [comment] 2021-07-27 19:58
Thanks for answering! That's what I do currently. Sorry I haven't looked into source code before.
Now I am thinking why not wrap 
https://github.com/arnelenero/simpler-state/blob/ebf66db69390cf5a0d12d77d07b5f6f9030180d8/src/useEntity.js#L28
with
```js
useIsoEffect(() => {
    subscriberFn(entity._value)
}, [transform]);
```
Because that way you don't need to call `subscriberFn` every re-render if you just need to update it when `transform` changes
I've updated my codesandbox. Thanks.

**Comment by arnelenero** [comment] 2021-07-28 02:49
Thanks for the suggestion.  It might work to just combine these:
```
  useIsoEffect(() => entity._subscribe(subscriberFn), [subscriberFn, entity])

  // Re-sync state in case transform function has changed
  subscriberFn(entity._value)
  ```
  
into 

```
  useIsoEffect(() => {
     // Re-sync state in case transform function has changed
     subscriberFn(entity._value)
  
     return entity._subscribe(subscriberFn)
  }, [subscriberFn, entity])
```

I will have to run tests against this, though.

**Comment by arnelenero** [comment] 2022-02-20 14:51
After revisiting this, the original code, where the `subscriberFn` is called to resync state in case the transform function has changed, is indeed intentional and safe.  It will not cause any re-render unconditionally because `subscriberFn` performs comparison with current entity value.

**Comment by arnelenero** [comment] 2022-02-20 14:59
After revisiting this I can confirm that the original code, where the `subscriberFn` is called to re-sync state in case the transform function has changed, is indeed intentional and safe.  It will not cause any re-render unconditionally because `subscriberFn` performs comparison with current entity value.  Therefore, the discussed enhancement above would not provide the intended result.

There has been no reported issues that are similar to the original issue reported here, and the original sandbox currently appears to be working as intended.

Due to the above, I am closing this issue.  We can reopen if a similar issue resurfaces.

**Closed by arnelenero** 2022-02-20 14:59 UTC
Labels: discussion
